In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from functions import *
import sys, os

## Sundstrom et al. 2025
https://arxiv.org/pdf/2505.04577 

https://github.com/msundstrom33/ComparingActiveLearningMethods

In [2]:
### Taking the average of COPUS COPUS_codes_sundstrom_weir across multiple observations of the same class

path = 'Published Data/Sundstrom_2025_data/data/classroom-observations/'

COPUS_sundstrom = pd.DataFrame()
unique_courses = []

#Get course name
for file in os.listdir(path):
    name = file.split('.')[0]
    name = file.split('_')
    unique_courses.append(name[0] + '_' + name[1])

unique_courses = list(set(unique_courses))
#if starts with 'LPA' remove, these are analysis files
unique_courses = [course for course in unique_courses if not course.startswith('LPA')]

for course in unique_courses:
    course_files = [f for f in os.listdir(path) if f.startswith(course)]
    course_data = pd.DataFrame()
    
    #stack all observations for a given class into one dataframe
    for file in course_files:
        data = pd.read_csv(os.path.join(path, file), index_col=0, header=8)
        #drop unnamed columns
        data = data.loc[:, ~data.columns.str.contains('^Unnamed')]
        #drop last 5 columns
        data = data.iloc[:, :-5]
        
        #drop rows where L is L ( get rid of non-numeric rows)
        data = data[data['L'] != 'L']
          
        #remove all nan columns and rows
        data = data.dropna(axis=0, how='all')
        course_data = pd.concat([course_data, data], ignore_index=True)
    #replace nans with 0
    course_data = course_data.infer_objects(copy = False).fillna(0)
    #make all values numeric
    course_data = course_data.apply(pd.to_numeric, errors='coerce')

    #find total length of observations
    Tot = len(course_data)
    #average all and add to COPUS_sundstrom
    COPUS_sundstrom = pd.concat([COPUS_sundstrom, course_data.mean().to_frame().T], ignore_index=True)
    #add total number of observations to COPUS_sundstrom
    COPUS_sundstrom.loc[len(COPUS_sundstrom)-1, 'Total'] = Tot
    #make first column the course_id
    COPUS_sundstrom.loc[len(COPUS_sundstrom)-1, 'Course'] = course

#make 'Course' the first column
cols = COPUS_sundstrom.columns.tolist()
cols = ['Course'] + [col for col in cols if col != 'Course']
COPUS_sundstrom = COPUS_sundstrom[cols]
#sort by course
COPUS_sundstrom = COPUS_sundstrom.sort_values('Course').reset_index(drop=True)

In [6]:
## Loading in concept inventory data
path = 'Published Data/Sundstrom_2025_data/data/rosters/'

CI_statistics_sundstrom = pd.DataFrame()
CI_statistics_sundstrom['Course'] = COPUS_sundstrom['Course']

max_scores = np.array([30, 30, 30, 30, 47, 0,##ISLE
 47, 47, 26, 26, 14, 30, 50, 47, 30, ##PI
 0, 0, 30, 30, 30, 30, 25, ##scale up
 26, 47, 33, 30, 26, 30, 30, 0]) ## Tutorials

courses = CI_statistics_sundstrom['Course'].values
for i in range(len(courses)):
    course = courses[i]

    #read in scores for the course
    file = path + 'Roster_' + course + '.csv'

    try:  #some COPUS courses do not have CI data
        CI_scores = pd.read_csv(path + 'Roster_' + course + '.csv')
        #get the class size
        N = int(len(CI_scores))
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'Class Size'] = N

        #We are only using matched scores, so we drop any rows with missing pre or post scores
        CI_scores.dropna(inplace = True)

        #get number of matched scores
        N = int(len(CI_scores))
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'N'] = N

        pretest_scores = CI_scores['PreScore'].values/max_scores[i]
        posttest_scores = CI_scores['PostScore'].values/max_scores[i]
        gains = posttest_scores - pretest_scores
        #correlation between pre scores and gains
        norm_pretest = (pretest_scores - np.mean(pretest_scores)) / np.std(pretest_scores)
        norm_gains = (gains - np.mean(gains)) / np.std(gains)
        m, b = np.polyfit(pretest_scores, norm_gains, 1)
        gain_correlation = np.corrcoef(pretest_scores, gains)[0, 1]

        #add means and STDs to CI_statistics_sundstrom
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'PreMean'] = np.mean(pretest_scores)
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'PreStd'] = np.std(pretest_scores)
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'PostMean'] = np.mean(posttest_scores)
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'PostStd'] = np.std(posttest_scores)
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'GainMean'] = np.mean(gains)
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'GainStd'] = np.std(gains)
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'GainCorrelation'] = gain_correlation
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'GainSlope'] = m
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'Equity Factor'] = (
            np.std(posttest_scores)**2 - np.std(pretest_scores)**2)/(np.std(pretest_scores) )
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'Gain'] = np.mean(gains)
    except:
        #If there is no CI data for the course, we remove it from the CI_statistics_sundstrom dataframe
        CI_statistics_sundstrom = CI_statistics_sundstrom[CI_statistics_sundstrom['Course'] != course]

#calculate effect sizes and add to CI_statistics_sundstrom
CI_statistics_sundstrom['Effect Size'] = [effect_size(CI_statistics_sundstrom['PreMean'].iloc[i],
                                         CI_statistics_sundstrom['PostMean'].iloc[i],
                                         CI_statistics_sundstrom['PreStd'].iloc[i],
                                         CI_statistics_sundstrom['PostStd'].iloc[i],
                                         CI_statistics_sundstrom['N'].iloc[i])
                                           for i in range(len(CI_statistics_sundstrom))]
#mark all courses as physics by default, then change to astronomy for the two astronomy courses
CI_statistics_sundstrom['Field'] = 'Physics'
astro_courses = ['Tutorials_Course2', 'Tutorials_Course6',]
CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'].isin(astro_courses), 'Field'] = 'Astronomy'

#mark source
CI_statistics_sundstrom['Source'] = 'Sundstrom et al. 2025'

sundstrom_combined = pd.merge(COPUS_sundstrom, CI_statistics_sundstrom, on='Course')
#save to csv
sundstrom_combined.to_csv('Published Data/Sundstrom_2025_data/combined_sundstrom_data.csv', index=False)

## Weir et al. 2019

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0220900

In [34]:
path = 'Published Data/Weir_2019_data/'

#read in COPUS codes
file = pd.ExcelFile(path + 'UBC_raw_COPUS.xlsx')
COPUS_codes_weir = pd.read_excel(file, sheet_name=file.sheet_names[-1])

#select only relevant columns, rename them, and convert values to percentages
COPUS_codes_weir = COPUS_codes_weir[['unique.section','num.students', 'ICQ', 'IPQ','SL', 'Ilec', 'SCG', 'SWG', 'SOG', 'SQ', 'I1o1' ]]
COPUS_codes_weir.columns = ['Course', 'Class Size', 'CQ', 'PQ','L', 'Lec', 'CG', 'WG', 'OG', 'SQ', '1o1']

COPUS_codes_weir.iloc[:, 2:] = COPUS_codes_weir.iloc[:, 2:].div(100)
COPUS_codes_weir['Field'] = 'Biology'

In [35]:
# load in CI statistics


CI_statistics_weir = pd.DataFrame()
#load raw scores, keep only relevant columns, convert to percentages
raw_scores = pd.read_excel(path + 'UBC_raw_scores.xlsx')
raw_scores.drop(columns=['course.level', 'term'], inplace=True)
raw_scores.iloc[:, 1:] = raw_scores.iloc[:, 1:].div(100)

course_list = raw_scores['unique.section'].unique()
for course in course_list:
    course_scores = raw_scores[raw_scores['unique.section'] == course]
    
    pretest_scores = course_scores['pre.score'].values
    posttest_scores = course_scores['post.score'].values
    CI_statistics_weir.loc[CI_statistics_weir.shape[0], 'Course'] = course
    CI_statistics_weir.loc[CI_statistics_weir.shape[0]-1, 'PreMean'] = np.mean(pretest_scores)
    CI_statistics_weir.loc[CI_statistics_weir.shape[0]-1, 'PreStd'] = np.std(pretest_scores)
    CI_statistics_weir.loc[CI_statistics_weir.shape[0]-1, 'PostMean'] = np.mean(posttest_scores)
    CI_statistics_weir.loc[CI_statistics_weir.shape[0]-1, 'PostStd'] = np.std(posttest_scores)
    CI_statistics_weir.loc[CI_statistics_weir.shape[0]-1, 'N'] = len(course_scores)

CI_statistics_weir['Effect Size'] = [effect_size(CI_statistics_weir['PreMean'].iloc[i],
                                         CI_statistics_weir['PostMean'].iloc[i],
                                         CI_statistics_weir['PreStd'].iloc[i],
                                         CI_statistics_weir['PostStd'].iloc[i],
                                         CI_statistics_weir['N'].iloc[i])
                                     for i in range(len(CI_statistics_weir))]

CI_statistics_weir['Source'] = 'Weir et al. 2019'

In [36]:
## combine COPUS codes with CI statistics
weir_combined = pd.merge(COPUS_codes_weir, CI_statistics_weir, on = 'Course')
weir_combined

,Course,Class Size,CQ,PQ,L,Lec,CG,WG,OG,SQ,1o1,Field,PreMean,PreStd,PostMean,PostStd,N,Effect Size,Source
0,1A,303,0.305250,0.344750,0.817000,0.532750,0.255500,0.263250,0.049750,0.211750,0.000000,Biology,0.322528,0.165109,0.821839,0.178042,199.0,2.897120,Weir et al. 2019
1,1B,251,0.301000,0.196167,0.934500,0.875000,0.234500,0.062500,0.000000,0.094500,0.000000,Biology,0.464645,0.246937,0.790243,0.177240,107.0,1.504246,Weir et al. 2019
2,1C,310,0.357667,0.303000,0.802667,0.565000,0.324667,0.187333,0.098667,0.156333,0.058667,Biology,0.307833,0.165856,0.801228,0.203690,215.0,2.647116,Weir et al. 2019
3,1D,296,0.339000,0.408000,0.905667,0.677667,0.319000,0.120000,0.147667,0.285000,0.000000,Biology,0.288056,0.176536,0.787386,0.185245,197.0,2.749085,Weir et al. 2019
4,2A,168,0.074000,0.320500,0.888000,0.333000,0.061500,0.000000,0.223500,0.159500,0.000000,Biology,0.464674,0.117792,0.631114,0.124880,64.0,1.355015,Weir et al. 2019
5,2B,225,0.497667,0.211333,0.902667,0.398667,0.412333,0.000000,0.136667,0.124333,0.000000,Biology,0.453623,0.101149,0.581159,0.137940,60.0,1.041205,Weir et al. 2019
6,2C,224,0.026667,0.140333,0.913000,0.730333,0.026667,0.000000,0.157000,0.080000,0.000000,Biology,0.441176,0.117723,0.620524,0.134161,136.0,1.413174,Weir et al. 2019
7,2D,217,0.053000,0.518000,0.706000,0.116500,0.053000,0.155500,0.177000,0.178500,0.027000,Biology,0.457005,0.143945,0.616425,0.177568,45.0,0.969780,Weir et al. 2019
8,2D2,234,0.164667,0.272333,0.666000,0.193667,0.013333,0.239333,0.215667,0.026667,0.000000,Biology,0.428668,0.090246,0.648777,0.148700,64.0,1.768510,Weir et al. 2019
9,2E,230,0.204333,0.406000,0.730000,0.216000,0.067667,0.186667,0.149333,0.095667,0.000000,Biology,0.457868,0.106038,0.651020,0.140077,113.0,1.544456,Weir et al. 2019
10,2F,213,0.131500,0.197500,0.895000,0.276500,0.026000,0.000000,0.355000,0.079000,0.000000,Biology,0.455279,0.094035,0.595031,0.123313,70.0,1.260751,Weir et al. 2019
11,2G,221,0.012000,0.367667,0.743000,0.473000,0.012000,0.000000,0.199000,0.221000,0.000000,Biology,0.442547,0.137394,0.639752,0.143782,112.0,1.392940,Weir et al. 2019
12,2H,168,0.229333,0.185333,0.757667,0.387333,0.166667,0.000000,0.184000,0.088333,0.049667,Biology,0.469388,0.101294,0.573203,0.141820,49.0,0.829464,Weir et al. 2019
13,3A,246,0.172500,0.462000,0.841500,0.481000,0.144000,0.000000,0.199500,0.108500,0.025500,Biology,0.484529,0.188437,0.689873,0.187537,158.0,1.087138,Weir et al. 2019
14,3B,245,0.267333,0.320667,0.911000,0.588000,0.234000,0.000000,0.151000,0.058667,0.000000,Biology,0.463432,0.196147,0.668073,0.197653,158.0,1.034368,Weir et al. 2019
15,3C,256,0.266667,0.550000,0.920000,0.486667,0.240000,0.000000,0.233333,0.303333,0.000000,Biology,0.463624,0.176931,0.637566,0.210413,168.0,0.890788,Weir et al. 2019
16,3D,209,0.159500,0.188000,0.985500,0.855000,0.145000,0.000000,0.000000,0.043000,0.000000,Biology,0.487542,0.188953,0.529966,0.314894,165.0,0.162631,Weir et al. 2019
17,3E,253,0.287333,0.424667,0.789667,0.387333,0.259333,0.000000,0.160333,0.190333,0.000000,Biology,0.451016,0.167035,0.634409,0.212812,186.0,0.954809,Weir et al. 2019
18,4A,551,0.329667,0.437333,0.879000,0.453333,0.316333,0.000000,0.243333,0.096000,0.000000,Biology,0.426462,0.159156,0.642462,0.181227,325.0,1.263575,Weir et al. 2019
19,5A,148,0.135667,0.067333,0.502333,0.245000,0.135667,0.240000,0.163333,0.000000,0.134333,Biology,0.444762,0.182602,0.661905,0.204152,150.0,1.115546,Weir et al. 2019
20,5B,349,0.237333,0.320000,0.851667,0.514333,0.189333,0.086667,0.014000,0.161667,0.033333,Biology,0.447545,0.172718,0.817336,0.167293,224.0,2.167608,Weir et al. 2019
21,6A,277,0.253250,0.082000,0.910750,0.666500,0.185750,0.000000,0.129500,0.237000,0.013500,Biology,0.502334,0.159120,0.654217,0.160566,189.0,0.946418,Weir et al. 2019
22,7A,120,0.229000,0.416000,0.986000,0.756000,0.173333,0.000000,0.189000,0.052667,0.000000,Biology,0.524457,0.183600,0.573370,0.215840,46.0,0.240112,Weir et al. 2019
23,8A,238,0.000000,0.000000,1.000000,0.963333,0.000000,0.000000,0.000000,0.059333,0.000000,Biology,0.496026,0.146428,0.656954,0.148060,151.0,1.087473,Weir et al. 2019
24,9A,219,0.144833,0.186333,0.978833,0.858667,0.144833,0.000000,0.000000,0.090000,0.000000,Biology,0.399194,0.152736,0.565860,0.173990,62.0,1.005705,Weir et al. 2019
25,10A,227,0.108500,0.578000,0.877500,0.582000,0.108500,0.000000,0.243000,0.250000,0.045500,Biology,0.782468,0.185444,0.871212,0.178703,154.0,0.484950,Weir et al. 2019
26,11A,73,0.104000,0.309000,0.577333,0.370333,0.113333,0.000000,0.515667,0.074333,0.183333,Biology,0.457500,0.211557,0.597500,0.190870,50.0,0.684387,Weir et al. 2019
27,12A,19,0.000000,0.187500,1.000000,1.000000,0.000000,0.000000,0.000000,0.062500,0.000000,Biology,0.500000,0.141639,0.638889,0.124226,9.0,0.953210,Weir et al. 2019
28,13A,19,0.040667,0.397333,0.972333,0.537333,0.000000,0.000000,0.055667,0.274333,0.000000,Biology,0.518519,0.151014,0.620370,0.142243,9.0,0.634801,Weir et al. 2019
29,14A,12,0.000000,0.573333,0.987333,0.772333,0.000000,0.000000,0.038333,0.403000,0.039333,Biology,0.638889,0.238953,0.736111,0.216060,9.0,0.390215,Weir et al. 2019
30,15A,35,0.000000,0.269333,0.783333,0.284000,0.000000,0.093333,0.325000,0.161667,0.014000,Biology,0.416667,0.166428,0.528571,0.185531,21.0,0.612011,Weir et al. 2019

## Connell et al 2017

https://www.lifescied.org/doi/full/10.1187/cbe.15-03-0062

In [37]:
#These values come from using webplot digitizer on from the graph  of COPUS codes in Connell et al. 2017
connell_combined = pd.DataFrame({
    'Course': ['Connell_ext', 'Connell_mod'],
    'L': [.65, .87],
    'Lec': [0.34, 0.75], #
    'PQ': [0.26, 0.28],#
    'MG': [0.31, 0.0], #
    'CQ': [0.0, 0.0], #not reported
    '1o1': [.318, .004],
    
    
    'CG': [0, 0], #not reported
    'WG': [0.4, 0.0],
    'OG': [0.12, 0.66], 
    'SQ': [0.12, 0.024], 
    
    'PreMean': [0.443, 0.429],
    'PostMean': [0.585, 0.546],
    'PreStd': [0.107, 0.104],
    'PostStd': [0.121, 0.122],

    'Class Size': [182, 172], 
    'N' : [158, 142],
    'Field': ['Biology', 'Biology'],
})

connell_combined['Effect Size'] = [effect_size(connell_combined['PreMean'].iloc[i],
                                         connell_combined['PostMean'].iloc[i],
                                         connell_combined['PreStd'].iloc[i],
                                         connell_combined['PostStd'].iloc[i],
                                         connell_combined['N'].iloc[i])
                                     for i in range(len(connell_combined))]

connell_combined['Source'] = 'Connell et al. 2017'
connell_combined

,Course,L,Lec,PQ,MG,CQ,1o1,CG,WG,OG,SQ,PreMean,PostMean,PreStd,PostStd,Class Size,N,Field,Effect Size,Source
0,Connell_ext,0.65,0.34,0.26,0.31,0.0,0.318,0,0.4,0.12,0.120,0.443,0.585,0.107,0.121,182,158,Biology,1.237361,Connell et al. 2017
1,Connell_mod,0.87,0.75,0.28,0.00,0.0,0.004,0,0.0,0.66,0.024,0.429,0.546,0.104,0.122,172,142,Biology,1.026669,Connell et al. 2017

### New data

In [38]:
measured_data = pd.read_csv('Measured Data/measured_data.csv')
measured_data['Source'] = 'Measured Data'

#where class size is unknown, fill with number of matched responses
class_size = measured_data['Class Size'].values
class_size[np.isnan(class_size)] = measured_data['N'].values[np.isnan(class_size)]
measured_data['Class Size'] = class_size

measured_data['Effect Size'] = [effect_size(measured_data['PreMean'].iloc[i],
                                         measured_data['PostMean'].iloc[i],
                                         measured_data['PreStd'].iloc[i],
                                         measured_data['PostStd'].iloc[i],
                                         measured_data['N'].iloc[i])
                                     for i in range(len(measured_data))]

#change field "astro" to "astronomy"
measured_data['Field'] = measured_data['Field'].replace('Astro', 'Astronomy')

## Combining Alll Datasets

In [39]:
all_data = pd.concat([sundstrom_combined, weir_combined, connell_combined, measured_data], ignore_index=True)
#reorder columns
#We keep these 8 COPUS codes because they were found by Stains et al (2018) to be the most informative for characterizing STEM classrooms
all_data = all_data[['Source', 'Course', 'N', 'Class Size', 'Field', 'PreMean', 'PostMean', 'PreStd', 'PostStd', 'Effect Size',
                                         'Lec', 'CG', 'CQ', 'PQ', 'WG', 'OG', 'SQ', '1o1' ]]

#When the mean of pretest scores is above 60, it imposes a ceiling effect on effect sizes
# and indicates that the CI may not be appropriate for that course, so we remove those courses
all_data = all_data[all_data['PreMean'] <= 0.6]


#compute effect size variance based on class size and effect size
def variance_on_d(N, d):
    return (2 * N) / N**2  + (d**2 / (4 * N))

all_data['Effect Size Variance'] = [variance_on_d(all_data['N'].iloc[i], all_data['Effect Size'].iloc[i]) for i in range(len(all_data))]

#saved combined data to csv
all_data.to_csv('combined_COPUS_CI_data.csv', index=False)