In [38]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from functions import *
import sys, os

## Sundstrom et al. 2025
https://arxiv.org/pdf/2505.04577 

https://github.com/msundstrom33/ComparingActiveLearningMethods

In [39]:
### Taking the average of COPUS COPUS_codes_sundstrom_weir across multiple observations of the same class

path = 'Published Data/Sundstrom_2025_data/'


#load in COPUS COPUS_codes_weir
COPUS_codes_sundstrom = pd.read_csv(path + 'data/classroom-observations/LPA_Input.csv')
#delete rows where course is nan
COPUS_codes_sundstrom = COPUS_codes_sundstrom.dropna(subset=['Course'])
#create a new column that combines the course and method columns
COPUS_codes_sundstrom['Course'] = [str(COPUS_codes_sundstrom['Method'].iloc[i]) + '_Course' + str(int(COPUS_codes_sundstrom['Course'].iloc[i])) for i in range(len(COPUS_codes_sundstrom))]
#for each group of rows that have the same method and course, take the mean of the numeric values
numeric_cols = COPUS_codes_sundstrom.select_dtypes(include='number').columns
COPUS_codes_sundstrom = COPUS_codes_sundstrom.groupby(['Course'])[numeric_cols].mean().reset_index()

In [40]:
## Loading in concept inventory data

CI_statistics_sundstrom = pd.DataFrame()
CI_statistics_sundstrom['Course'] = COPUS_codes_sundstrom['Course']

max_scores = np.array([30, 30, 30, 30, 47, 0,##ISLE
 47, 47, 26, 26, 14, 30, 50, 47, 30, ##PI
 0, 0, 30, 30, 30, 30, 25, ##scale up
 26, 47, 33, 30, 26, 30, 30, 0]) ## Tutorials

courses = CI_statistics_sundstrom['Course'].values
for i in range(len(courses)):
    course = courses[i]

    #read in scores for the course
    file = path + 'data/rosters/Roster_' + course + '.csv'

    try:  #some COPUS courses do not have CI data
        CI_scores = pd.read_csv(path + 'data/rosters/Roster_' + course + '.csv')
        #input the class size
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'N'] = int(len(CI_scores))

        #We are only using matched scores, so we drop any rows with missing pre or post scores
        CI_scores.dropna(inplace = True)

        pretest_scores = CI_scores['PreScore'].values/max_scores[i]
        posttest_scores = CI_scores['PostScore'].values/max_scores[i]

        #add means and STDs to CI_statistics_sundstrom
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'PreMean'] = np.mean(pretest_scores)
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'PreStd'] = np.std(pretest_scores)
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'PostMean'] = np.mean(posttest_scores)
        CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'] == course, 'PostStd'] = np.std(posttest_scores)
    except:
        #If there is no CI data for the course, we remove it from the CI_statistics_sundstrom dataframe
        CI_statistics_sundstrom = CI_statistics_sundstrom[CI_statistics_sundstrom['Course'] != course]

#calculate effect sizes and add to CI_statistics_sundstrom
CI_statistics_sundstrom['Effect Size'] = [effect_size(CI_statistics_sundstrom['PreMean'].iloc[i],
                                         CI_statistics_sundstrom['PostMean'].iloc[i],
                                         CI_statistics_sundstrom['PreStd'].iloc[i],
                                         CI_statistics_sundstrom['PostStd'].iloc[i]) for i in range(len(CI_statistics_sundstrom))]

CI_statistics_sundstrom['Field'] = 'Physics'
astro_courses = ['Tutorials_Course2', 'Tutorials_Course6',]
CI_statistics_sundstrom.loc[CI_statistics_sundstrom['Course'].isin(astro_courses), 'Field'] = 'Astronomy'

In [41]:
## combine COPUS COPUS_codes_weir with CI statistics
sundstrom_combined = pd.merge(COPUS_codes_sundstrom, CI_statistics_sundstrom, on='Course')
sundstrom_combined

,Course,CQ,MG,PQ,Lec,CG,WG,OG,SQ,N,PreMean,PreStd,PostMean,PostStd,Effect Size,Field
0,ISLE_Course1,0.178884,0.009804,0.811526,0.407428,0.162004,0.000000,0.145035,0.198617,150.0,0.278744,0.177654,0.441546,0.195802,0.870839,Physics
1,ISLE_Course2,0.056778,0.154216,0.222885,0.622976,0.000000,0.105691,0.034278,0.148590,16.0,0.413889,0.195533,0.461111,0.207201,0.234410,Physics
2,ISLE_Course3,0.253070,0.008772,0.704386,0.539474,0.128070,0.000000,0.100439,0.260526,118.0,0.345318,0.205252,0.423596,0.175190,0.410227,Physics
3,ISLE_Course4,0.000000,0.481863,0.910784,0.116667,0.000000,0.425000,0.102941,0.269608,15.0,0.423810,0.232457,0.645238,0.213663,0.991806,Physics
4,ISLE_Course5,0.000000,0.591475,0.859631,0.167351,0.000000,0.347034,0.244442,0.006410,32.0,0.248227,0.090269,0.476359,0.290706,1.059888,Physics
5,PeerInstruction_Course1,0.020202,0.058923,0.840132,0.886817,0.020202,0.000000,0.106643,0.230122,28.0,0.440729,0.184920,0.498480,0.203398,0.297105,Physics
6,PeerInstruction_Course2,0.339023,0.356330,0.661925,0.446420,0.266951,0.000000,0.071124,0.036036,263.0,0.252077,0.165272,0.359068,0.260662,0.490239,Physics
7,PeerInstruction_Course3,0.658333,0.430556,0.274444,0.489444,0.617222,0.027778,0.000000,0.000000,576.0,0.402808,0.194549,0.457979,0.255339,0.243057,Physics
8,PeerInstruction_Course4,0.471985,0.416904,0.178181,0.436135,0.404677,0.000000,0.025641,0.039530,201.0,0.527939,0.188314,0.574383,0.267998,0.200529,Physics
9,PeerInstruction_Course5,0.452727,0.283636,0.347879,0.471515,0.412727,0.000000,0.053333,0.055152,81.0,0.282143,0.203884,0.370238,0.217629,0.417773,Physics
10,PeerInstruction_Course6,0.436534,0.123246,0.459063,0.205709,0.300230,0.000000,0.078725,0.043369,94.0,0.417949,0.169648,0.616667,0.203443,1.060910,Physics
11,PeerInstruction_Course7,0.046512,0.170457,0.640655,0.610465,0.023256,0.000000,0.187705,0.107623,17.0,0.382400,0.136361,0.622400,0.178294,1.512111,Physics
12,PeerInstruction_Course8,0.414835,0.271062,0.366300,0.362637,0.379121,0.000000,0.000000,0.173993,319.0,0.487611,0.281615,0.774037,0.253547,1.068958,Physics
13,PeerInstruction_Course9,0.323973,0.047619,0.189180,0.572533,0.261137,0.000000,0.000000,0.046131,20.0,0.283333,0.091504,0.373810,0.171445,0.658410,Physics
14,SCALEUP_Course3,0.000000,0.812221,0.947712,0.047839,0.000000,0.000000,0.841323,0.015159,135.0,0.270833,0.172939,0.528526,0.262565,1.159129,Physics
15,SCALEUP_Course4,0.000000,0.699565,0.865868,0.127721,0.000000,0.000000,0.712506,0.044751,23.0,0.229825,0.104235,0.400000,0.161499,1.252056,Physics
16,SCALEUP_Course5,0.005291,0.425957,0.643213,0.429426,0.000000,0.000000,0.442547,0.005848,99.0,0.245783,0.118187,0.374699,0.149930,0.954968,Physics
17,SCALEUP_Course6,0.251399,0.586041,0.528321,0.314685,0.244597,0.142857,0.274154,0.022922,48.0,0.302128,0.138449,0.686525,0.206474,2.186764,Physics
18,SCALEUP_Course7,0.000000,0.675944,0.862752,0.218846,0.000000,0.463711,0.186713,0.037413,42.0,0.363333,0.114843,0.532222,0.173543,1.147734,Physics
19,Tutorials_Course2,0.043860,0.516082,0.824074,0.193470,0.017544,0.442008,0.118421,0.203216,18.0,0.233974,0.123095,0.355769,0.136095,0.938629,Astronomy
20,Tutorials_Course3,0.000000,0.543486,0.753784,0.203064,0.000000,0.188889,0.422556,0.075651,36.0,0.258865,0.205949,0.406619,0.299379,0.575039,Physics
21,Tutorials_Course4,0.000000,1.000000,1.000000,0.026838,0.000000,1.000000,0.000000,0.000000,32.0,0.413019,0.117840,0.725028,0.149578,2.317230,Physics
22,Tutorials_Course5,0.000000,0.771744,0.953670,0.236347,0.000000,0.791000,0.000000,0.000000,49.0,0.278788,0.168938,0.421970,0.194358,0.786317,Physics
23,Tutorials_Course6,0.286325,0.000000,0.228124,0.672365,0.286325,0.000000,0.185389,0.164632,185.0,0.317405,0.153588,0.479021,0.178341,0.971104,Astronomy
24,Tutorials_Course7,0.000000,0.463611,0.862185,0.138224,0.000000,0.446002,0.099310,0.019048,29.0,0.352778,0.188050,0.412500,0.204761,0.303802,Physics
25,Tutorials_Course8,0.000000,0.900901,0.963964,0.000000,0.000000,0.909910,0.099099,0.045045,11.0,0.247619,0.070951,0.419048,0.147849,1.478343,Physics

## Weir et al. 2019

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0220900

In [42]:
path = 'Published Data/Weir_2019_data/'

#read in COPUS codes
file = pd.ExcelFile(path + 'UBC_raw_COPUS.xlsx')
COPUS_codes_weir = pd.read_excel(file, sheet_name=file.sheet_names[-1])

#select only relevant columns, rename them, and convert values to percentages
COPUS_codes_weir = COPUS_codes_weir[['unique.section','num.students', 'ICQ', 'IPQ','SL', 'Ilec', 'SCG', 'SWG', 'SOG', 'SQ',  ]]
COPUS_codes_weir.columns = ['Course', 'N', 'CQ', 'PQ','L', 'Lec', 'CG', 'WG', 'OG', 'SQ', ]

COPUS_codes_weir.iloc[:, 2:] = COPUS_codes_weir.iloc[:, 2:].div(100)
COPUS_codes_weir['Field'] = 'Biology'

In [43]:
# load in CI statistics


CI_statistics_weir = pd.DataFrame()
#load raw scores, keep only relevant columns, convert to percentages
raw_scores = pd.read_excel(path + 'UBC_raw_scores.xlsx')
raw_scores.drop(columns=['course.level', 'term'], inplace=True)
raw_scores.iloc[:, 1:] = raw_scores.iloc[:, 1:].div(100)

course_list = raw_scores['unique.section'].unique()
for course in course_list:
    course_scores = raw_scores[raw_scores['unique.section'] == course]
    pretest_scores = course_scores['pre.score'].values
    posttest_scores = course_scores['post.score'].values
    CI_statistics_weir.loc[CI_statistics_weir.shape[0], 'Course'] = course
    CI_statistics_weir.loc[CI_statistics_weir.shape[0]-1, 'PreMean'] = np.mean(pretest_scores)
    CI_statistics_weir.loc[CI_statistics_weir.shape[0]-1, 'PreStd'] = np.std(pretest_scores)
    CI_statistics_weir.loc[CI_statistics_weir.shape[0]-1, 'PostMean'] = np.mean(posttest_scores)
    CI_statistics_weir.loc[CI_statistics_weir.shape[0]-1, 'PostStd'] = np.std(posttest_scores)

CI_statistics_weir['Effect Size'] = [effect_size(CI_statistics_weir['PreMean'].iloc[i],
                                         CI_statistics_weir['PostMean'].iloc[i],
                                         CI_statistics_weir['PreStd'].iloc[i],
                                         CI_statistics_weir['PostStd'].iloc[i])
                                     for i in range(len(CI_statistics_weir))]

In [44]:
## combine COPUS codes with CI statistics
weir_combined = pd.merge(COPUS_codes_weir, CI_statistics_weir, on = 'Course')
weir_combined.head()

,Course,N,CQ,PQ,L,Lec,CG,WG,OG,SQ,Field,PreMean,PreStd,PostMean,PostStd,Effect Size
0,1A,303,0.305250,0.344750,0.817000,0.532750,0.255500,0.263250,0.049750,0.211750,Biology,0.322528,0.165109,0.821839,0.178042,2.908094
1,1B,251,0.301000,0.196167,0.934500,0.875000,0.234500,0.062500,0.000000,0.094500,Biology,0.464645,0.246937,0.790243,0.177240,1.514889
2,1C,310,0.357667,0.303000,0.802667,0.565000,0.324667,0.187333,0.098667,0.156333,Biology,0.307833,0.165856,0.801228,0.203690,2.656393
3,1D,296,0.339000,0.408000,0.905667,0.677667,0.319000,0.120000,0.147667,0.285000,Biology,0.288056,0.176536,0.787386,0.185245,2.759605
4,2A,168,0.074000,0.320500,0.888000,0.333000,0.061500,0.000000,0.223500,0.159500,Biology,0.464674,0.117792,0.631114,0.124880,1.371146

## Connell et al 2017

https://www.lifescied.org/doi/full/10.1187/cbe.15-03-0062

In [45]:
#These values come from using webplot digitizer on from the graph  of COPUS codes in Connell et al. 2017

connell_combined = pd.DataFrame({
    'Course': ['Connell_ext', 'Connell_mod'],
    'L': [.65, .87],
    'Lec': [0.34, 0.75], #
    'PQ': [0.26, 0.28],#
    'MG': [0.31, 0.0], #
    'CQ': [0.0, 0.0], #not reported
    
    
    'CG': [0, 0], #not reported
    'WG': [0.4, 0.0],
    'OG': [0.12, 0.66], 
    'SQ': [0.12, 0.024], 
    
    'PreMean': [0.443, 0.429],
    'PostMean': [0.585, 0.546],
    'PreStd': [0.107, 0.104],
    'PostStd': [0.121, 0.122],
    'Class Size': [182, 172], #reported 316 took survey

    'N': [182, 172], #reported 316 took survey
    'Field': ['Biology', 'Biology'],
})

connell_combined['Effect Size'] = (connell_combined['PostMean'] - connell_combined['PreMean']) / np.sqrt(
    (connell_combined['PreStd']**2 + connell_combined['PostStd']**2) / 2)

connell_combined

,Course,L,Lec,PQ,MG,CQ,CG,WG,OG,SQ,PreMean,PostMean,PreStd,PostStd,Class Size,N,Field,Effect Size
0,Connell_ext,0.65,0.34,0.26,0.31,0.0,0,0.4,0.12,0.120,0.443,0.585,0.107,0.121,182,182,Biology,1.243272
1,Connell_mod,0.87,0.75,0.28,0.00,0.0,0,0.0,0.66,0.024,0.429,0.546,0.104,0.122,172,172,Biology,1.032130

## Combining Alll Datasets

In [48]:
all_data = pd.concat([sundstrom_combined, weir_combined, connell_combined], ignore_index=True)

#reorder columns
#we remove MG because it was only reported by Sundstrom not the others
all_data = all_data[['Course', 'N', 'Field', 'PreMean', 'PostMean', 'PreStd', 'PostStd', 'Effect Size',
                                        'L', 'Lec', 'CG', 'CQ', 'PQ', 'WG', 'OG', 'SQ', ]]

#When the mean of pretest scores is above 60, it imposes a ceiling effect on effect sizes
# and indicates that the CI may not be appropriate for that course, so we remove those courses
all_data = all_data[all_data['PreMean'] <= 0.6]

#saved combined data to csv
all_data.to_csv('Published Data/combined_COPUS_CI_data.csv', index=False)
all_data

,Course,N,Field,PreMean,PostMean,PreStd,PostStd,Effect Size,L,Lec,CG,CQ,PQ,WG,OG,SQ
0,ISLE_Course1,150.0,Physics,0.278744,0.441546,0.177654,0.195802,0.870839,NaN,0.407428,0.162004,0.178884,0.811526,0.000000,0.145035,0.198617
1,ISLE_Course2,16.0,Physics,0.413889,0.461111,0.195533,0.207201,0.234410,NaN,0.622976,0.000000,0.056778,0.222885,0.105691,0.034278,0.148590
2,ISLE_Course3,118.0,Physics,0.345318,0.423596,0.205252,0.175190,0.410227,NaN,0.539474,0.128070,0.253070,0.704386,0.000000,0.100439,0.260526
3,ISLE_Course4,15.0,Physics,0.423810,0.645238,0.232457,0.213663,0.991806,NaN,0.116667,0.000000,0.000000,0.910784,0.425000,0.102941,0.269608
4,ISLE_Course5,32.0,Physics,0.248227,0.476359,0.090269,0.290706,1.059888,NaN,0.167351,0.000000,0.000000,0.859631,0.347034,0.244442,0.006410
5,PeerInstruction_Course1,28.0,Physics,0.440729,0.498480,0.184920,0.203398,0.297105,NaN,0.886817,0.020202,0.020202,0.840132,0.000000,0.106643,0.230122
6,PeerInstruction_Course2,263.0,Physics,0.252077,0.359068,0.165272,0.260662,0.490239,NaN,0.446420,0.266951,0.339023,0.661925,0.000000,0.071124,0.036036
7,PeerInstruction_Course3,576.0,Physics,0.402808,0.457979,0.194549,0.255339,0.243057,NaN,0.489444,0.617222,0.658333,0.274444,0.027778,0.000000,0.000000
8,PeerInstruction_Course4,201.0,Physics,0.527939,0.574383,0.188314,0.267998,0.200529,NaN,0.436135,0.404677,0.471985,0.178181,0.000000,0.025641,0.039530
9,PeerInstruction_Course5,81.0,Physics,0.282143,0.370238,0.203884,0.217629,0.417773,NaN,0.471515,0.412727,0.452727,0.347879,0.000000,0.053333,0.055152
10,PeerInstruction_Course6,94.0,Physics,0.417949,0.616667,0.169648,0.203443,1.060910,NaN,0.205709,0.300230,0.436534,0.459063,0.000000,0.078725,0.043369
11,PeerInstruction_Course7,17.0,Physics,0.382400,0.622400,0.136361,0.178294,1.512111,NaN,0.610465,0.023256,0.046512,0.640655,0.000000,0.187705,0.107623
12,PeerInstruction_Course8,319.0,Physics,0.487611,0.774037,0.281615,0.253547,1.068958,NaN,0.362637,0.379121,0.414835,0.366300,0.000000,0.000000,0.173993
13,PeerInstruction_Course9,20.0,Physics,0.283333,0.373810,0.091504,0.171445,0.658410,NaN,0.572533,0.261137,0.323973,0.189180,0.000000,0.000000,0.046131
14,SCALEUP_Course3,135.0,Physics,0.270833,0.528526,0.172939,0.262565,1.159129,NaN,0.047839,0.000000,0.000000,0.947712,0.000000,0.841323,0.015159
15,SCALEUP_Course4,23.0,Physics,0.229825,0.400000,0.104235,0.161499,1.252056,NaN,0.127721,0.000000,0.000000,0.865868,0.000000,0.712506,0.044751
16,SCALEUP_Course5,99.0,Physics,0.245783,0.374699,0.118187,0.149930,0.954968,NaN,0.429426,0.000000,0.005291,0.643213,0.000000,0.442547,0.005848
17,SCALEUP_Course6,48.0,Physics,0.302128,0.686525,0.138449,0.206474,2.186764,NaN,0.314685,0.244597,0.251399,0.528321,0.142857,0.274154,0.022922
18,SCALEUP_Course7,42.0,Physics,0.363333,0.532222,0.114843,0.173543,1.147734,NaN,0.218846,0.000000,0.000000,0.862752,0.463711,0.186713,0.037413
19,Tutorials_Course2,18.0,Astronomy,0.233974,0.355769,0.123095,0.136095,0.938629,NaN,0.193470,0.017544,0.043860,0.824074,0.442008,0.118421,0.203216
20,Tutorials_Course3,36.0,Physics,0.258865,0.406619,0.205949,0.299379,0.575039,NaN,0.203064,0.000000,0.000000,0.753784,0.188889,0.422556,0.075651
21,Tutorials_Course4,32.0,Physics,0.413019,0.725028,0.117840,0.149578,2.317230,NaN,0.026838,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
22,Tutorials_Course5,49.0,Physics,0.278788,0.421970,0.168938,0.194358,0.786317,NaN,0.236347,0.000000,0.000000,0.953670,0.791000,0.000000,0.000000
23,Tutorials_Course6,185.0,Astronomy,0.317405,0.479021,0.153588,0.178341,0.971104,NaN,0.672365,0.286325,0.286325,0.228124,0.000000,0.185389,0.164632
24,Tutorials_Course7,29.0,Physics,0.352778,0.412500,0.188050,0.204761,0.303802,NaN,0.138224,0.000000,0.000000,0.862185,0.446002,0.099310,0.019048
25,Tutorials_Course8,11.0,Physics,0.247619,0.419048,0.070951,0.147849,1.478343,NaN,0.000000,0.000000,0.000000,0.963964,0.909910,0.099099,0.045045
26,1A,303.0,Biology,0.322528,0.821839,0.165109,0.178042,2.908094,0.817000,0.532750,0.255500,0.305250,0.344750,0.263250,0.049750,0.211750
27,1B,251.0,Biology,0.464645,0.790243,0.246937,0.177240,1.514889,0.934500,0.875000,0.234500,0.301000,0.196167,0.062500,0.000000,0.094500
28,1C,310.0,Biology,0.307833,0.801228,0.165856,0.203690,2.656393,0.802667,0.565000,0.324667,0.357667,0.303000,0.187333,0.098667,0.156333
29,1D,296.0,Biology,0.288056,0.787386,0.176536,0.185245,2.759605,0.905667,0.677667,0.319000,0.339000,0.408000,0.120000,0.147667,0.285000
30,2A,168.0,Biology,0.464674,0.631114,0.117792,0.124880,1.371146,0.888000,0.333000,0.061500,0.074000,0.320500,0.000000,0.223500,0.159500
31,2B,225.0,Biology,0.453623,0.581159,0.101149,0.137940,1.054441,0.902667,0.398667,0.412333,0.497667,0.211333,0.000000,0.136667,0.124333
32,2C,224.0,Biology,0.441176,0.620524,0.117723,0.134161,1.421025,0.913000,0.730333,0.026667,0.026667,0.140333,0.000000,0.157000,0.080000
33,2D,217.0,Biology,0.457005,0.616425,0.143945,0.177568,0.986310,0.706000,0.116500,0.053000,0.053000,0.518000,0.155500,0.177000,0.178500
34,2D2,234.0,Biology,0.428668,0.648777,0.090246,0.148700,1.789564,0.666000,0.193667,0.013333,0.164667,0.272333,0.239333,0.215667,0.026667
35,2E,230.0,Biology,0.457868,0.651020,0.106038,0.140077,1.554798,0.730000,0.216000,0.067667,0.204333,0.406000,0.186667,0.149333,0.095667
36,2F,213.0,Biology,0.455279,0.595031,0.094035,0.123313,1.274455,0.895000,0.276500,0.026000,0.131500,0.197500,0.000000,0.355000,0.079000
37,2G,221.0,Biology,0.442547,0.639752,0.137394,0.143782,1.402352,0.743000,0.473000,0.012000,0.012000,0.367667,0.000000,0.199000,0.221000
38,2H,168.0,Biology,0.469388,0.573203,0.101294,0.141820,0.842425,0.757667,0.387333,0.166667,0.229333,0.185333,0.000000,0.184000,0.088333
39,3A,246.0,Biology,0.484529,0.689873,0.188437,0.187537,1.092331,0.841500,0.481000,0.144000,0.172500,0.462000,0.000000,0.199500,0.108500
40,3B,245.0,Biology,0.463432,0.668073,0.196147,0.197653,1.039309,0.911000,0.588000,0.234000,0.267333,0.320667,0.000000,0.151000,0.058667
41,3C,256.0,Biology,0.463624,0.637566,0.176931,0.210413,0.894788,0.920000,0.486667,0.240000,0.266667,0.550000,0.000000,0.233333,0.303333
42,3D,209.0,Biology,0.487542,0.529966,0.188953,0.314894,0.163375,0.985500,0.855000,0.145000,0.159500,0.188000,0.000000,0.000000,0.043000
43,3E,253.0,Biology,0.451016,0.634409,0.167035,0.212812,0.958680,0.789667,0.387333,0.259333,0.287333,0.424667,0.000000,0.160333,0.190333
44,4A,551.0,Biology,0.426462,0.642462,0.159156,0.181227,1.266500,0.879000,0.453333,0.316333,0.329667,0.437333,0.000000,0.243333,0.096000
45,5A,148.0,Biology,0.444762,0.661905,0.182602,0.204152,1.121162,0.502333,0.245000,0.135667,0.135667,0.067333,0.240000,0.163333,0.000000
46,5B,349.0,Biology,0.447545,0.817336,0.172718,0.167293,2.174899,0.851667,0.514333,0.189333,0.237333,0.320000,0.086667,0.014000,0.161667
47,6A,277.0,Biology,0.502334,0.654217,0.159120,0.160566,0.950194,0.910750,0.666500,0.185750,0.253250,0.082000,0.000000,0.129500,0.237000
48,7A,120.0,Biology,0.524457,0.573370,0.183600,0.215840,0.244114,0.986000,0.756000,0.173333,0.229000,0.416000,0.000000,0.189000,0.052667
49,8A,238.0,Biology,0.496026,0.656954,0.146428,0.148060,1.092911,1.000000,0.963333,0.000000,0.000000,0.000000,0.000000,0.000000,0.059333
50,9A,219.0,Biology,0.399194,0.565860,0.152736,0.173990,1.018070,0.978833,0.858667,0.144833,0.144833,0.186333,0.000000,0.000000,0.090000
52,11A,73.0,Biology,0.457500,0.597500,0.211557,0.190870,0.694862,0.577333,0.370333,0.113333,0.104000,0.309000,0.000000,0.515667,0.074333
53,12A,19.0,Biology,0.500000,0.638889,0.141639,0.124226,1.042573,1.000000,1.000000,0.000000,0.000000,0.187500,0.000000,0.000000,0.062500
54,13A,19.0,Biology,0.518519,0.620370,0.151014,0.142243,0.694314,0.972333,0.537333,0.000000,0.040667,0.397333,0.000000,0.055667,0.274333
56,15A,35.0,Biology,0.416667,0.528571,0.166428,0.185531,0.634961,0.783333,0.284000,0.000000,0.000000,0.269333,0.093333,0.325000,0.161667
57,Connell_ext,182.0,Biology,0.443000,0.585000,0.107000,0.121000,1.243272,0.650000,0.340000,0.000000,0.000000,0.260000,0.400000,0.120000,0.120000
58,Connell_mod,172.0,Biology,0.429000,0.546000,0.104000,0.122000,1.032130,0.870000,0.750000,0.000000,0.000000,0.280000,0.000000,0.660000,0.024000